// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neembly.GPIDServer.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Neembly.GPIDServer.Persistence.Migrations.UtilsDB
{
    [DbContext(typeof(UtilsDBContext))]
    partial class UtilsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Neembly.GPIDServer.Persistence.Entities.EmailQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlindCarbonCopies")
                        .HasMaxLength(2000);

                    b.Property<string>("CarbonCopies")
                        .HasMaxLength(2000);

                    b.Property<string>("FailedMessage")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsHtml");

                    b.Property<string>("Message");

                    b.Property<string>("OperatorId");

                    b.Property<string>("Receipients")
                        .HasMaxLength(2000);

                    b.Property<string>("Sender")
                        .HasMaxLength(256);

                    b.Property<string>("Status")
                        .HasMaxLength(256);

                    b.Property<string>("Subject")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("EmailQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
